---
title: "R Notebook"
output: github_document
---

```{r}
library(dada2)
```

```{r}
install.packages("Rcpp")
```
```{r}
library(dada2)
packageVersion("dada2")
```
```{r}
path<- "/home/rstudio/essai/MiSeq_SOP"
list.files(path)
```

```{r}
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))
print(fnFs)
print(fnRs)
```


```{r}
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
print(sample.names)
```
```{r}
plotQualityProfile(fnFs[1:20])
plotQualityProfile(fnRs[1:20])

```

```{r}
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
print(filtFs)
print(filtRs)

```
```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)
print(out)
head(out)

```
```{r}
errF <- learnErrors(filtFs, multithread=TRUE)

```
```{r}
errR <- learnErrors(filtRs, multithread=TRUE)
```
```{r}
plotErrors(errF, nominalQ=TRUE)
```
```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
```





